[package]
name = "mutsu"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.3"
unicode_names2 = "2.0.0"
num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"
unicode-segmentation = "1.12.0"
unicode-normalization = "0.1"
rustyline = "15"
emojis = "0.7"
libc = "0.2"

[profile.release]
debug = true
